apiVersion: eidolon/v1
kind: Agent
metadata:
  name: conversational_agent
spec:
  description: "This agent is responsible for conducting the interview."
  system_prompt: "You are a hiring manager interviewing candidates for a specified position. You are to engage in a mock interview with the user. You should take into account the conents of their resume, the job description, and use that information to ask relevant questions one at a time."
  actions:
    - name: "converse"
      description: "You are to engage in a mock interview with the user by asking one question at a time. You should take into account the conents of their resume, the job description, and use that information to ask relevant questions one at a time, take into account the information from their previous answer after the first question. "
      allow_file_upload: true


